export enum CartType {
  ADD_PRODUCT_CART = "ADD_PRODUCT_CART",
  REMOVE_PRODUCT_CART = "REMOVE_PRODUCT_CART",
  UPDATE_PRODUCT_CART = "UPDATE_PRODUCT_CART",
  ADD_QTY_PRODUCT_CART = "ADD_QTY_PRODUCT_CART",
  LOAD_ALL_PRODUCTS = "LOAD_ALL_PRODUCTS",
  REMOVE_QTY_PRODUCT_CART = "REMOVE_QTY_PRODUCT_CART",
  REMOVE_ALL_PRODUCTS = "REMOVE_ALL_PRODUCTS",
  CLEAR_CART = "CLEAR_CART",
  CART_ERROR = "CART_ERROR",
}