export enum CustomerType {
  RETRIEVE_ALL = "RETRIEVE_ALL",
  RETRIEVE_SINGLE_CUSTOMER = "RETRIEVE_SINGLE_CUSTOMER",
  ADD = "ADD",
  EDIT = "EDIT",
  DELETE = "DELETE",
  CLEAR_CUSTOMERS = "CLEAR_CUSTOMERS",
  ERROR = "ERROR"
}