export enum OrderType {
  RETRIEVE_ALL_ORDERS = "RETRIEVE_ALL_ORDERS",
  RETRIEVE_SINGLE_ORDER = "RETRIEVE_SINGLE_ORDER",
  CONFIRM_PAYMENT = "CONFIRM_PAYMENT",
  ADD_ORDER = "ADD_ORDER",
  EDIT_ORDER = "EDIT_ORDER",
  DELETE_ORDER = "DELETE_ORDER",
  CLEAR_ORDERS = "CLEAR_ORDERS",
  ERROR_ORDER = "ERROR_ORDER"
}