export enum ProductType {
  RETRIEVE_ALL_PRODUCTS = "RETRIEVE_ALL_PRODUCTS",
  RETRIEVE_SINGLE_PRODUCT = "RETRIEVE_SINGLE_PRODUCT",
  ADD_PRODUCT = "ADD_PRODUCT",
  EDIT_PRODUCT = "EDIT_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  CLEAR_PRODUCTS = "CLEAR_PRODUCTS",
  ERROR_PRODUCT = "ERROR_PRODUCT"
}